const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

// IFZA Data
const ifzaData = [
    {
        "freezone": "IFZA",
        "product": "0 Visa License",
        "license_cost_including_quota_fee": 12900,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 0,
        "visa_cost_investor": 0,
        "visa_cost_manager": 0,
        "visa_cost_employment": 0,
        "immigration_establishment_card": 0,
        "e_channel_registration": 0,
        "medical_cost": 0,
        "eid_cost": 0,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "1 Visa License",
        "license_cost_including_quota_fee": 14900,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 1,
        "visa_cost_investor": 4750,
        "visa_cost_manager": 3750,
        "visa_cost_employment": 3750,
        "immigration_establishment_card": 1620,
        "e_channel_registration": 0,
        "medical_cost": 450,
        "eid_cost": 390,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "2 Visa License",
        "license_cost_including_quota_fee": 16900,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 2,
        "visa_cost_investor": 9500,
        "visa_cost_manager": 7500,
        "visa_cost_employment": 7500,
        "immigration_establishment_card": 3240,
        "e_channel_registration": 0,
        "medical_cost": 900,
        "eid_cost": 780,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "3 Visa License",
        "license_cost_including_quota_fee": 18900,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 3,
        "visa_cost_investor": 14250,
        "visa_cost_manager": 11250,
        "visa_cost_employment": 11250,
        "immigration_establishment_card": 4860,
        "e_channel_registration": 0,
        "medical_cost": 1350,
        "eid_cost": 1170,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "4 Visa License",
        "license_cost_including_quota_fee": 20900,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 4,
        "visa_cost_investor": 19000,
        "visa_cost_manager": 15000,
        "visa_cost_employment": 15000,
        "immigration_establishment_card": 6480,
        "e_channel_registration": 0,
        "medical_cost": 1800,
        "eid_cost": 1560,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "5 Visa License",
        "license_cost_including_quota_fee": 22900,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 5,
        "visa_cost_investor": 23750,
        "visa_cost_manager": 18750,
        "visa_cost_employment": 18750,
        "immigration_establishment_card": 8100,
        "e_channel_registration": 0,
        "medical_cost": 2250,
        "eid_cost": 1950,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "6 Visa License",
        "license_cost_including_quota_fee": 24900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 6,
        "visa_cost_investor": 28500,
        "visa_cost_manager": 22500,
        "visa_cost_employment": 22500,
        "immigration_establishment_card": 9720,
        "e_channel_registration": 0,
        "medical_cost": 2700,
        "eid_cost": 2340,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "7 Visa License",
        "license_cost_including_quota_fee": 26900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 7,
        "visa_cost_investor": 33250,
        "visa_cost_manager": 26250,
        "visa_cost_employment": 26250,
        "immigration_establishment_card": 11340,
        "e_channel_registration": 0,
        "medical_cost": 3150,
        "eid_cost": 2730,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "8 Visa License",
        "license_cost_including_quota_fee": 28900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 8,
        "visa_cost_investor": 38000,
        "visa_cost_manager": 30000,
        "visa_cost_employment": 30000,
        "immigration_establishment_card": 12960,
        "e_channel_registration": 0,
        "medical_cost": 3600,
        "eid_cost": 3120,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "9 Visa License",
        "license_cost_including_quota_fee": 30900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 9,
        "visa_cost_investor": 42750,
        "visa_cost_manager": 33750,
        "visa_cost_employment": 33750,
        "immigration_establishment_card": 14580,
        "e_channel_registration": 0,
        "medical_cost": 4050,
        "eid_cost": 3510,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "10 Visa License",
        "license_cost_including_quota_fee": 32900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 10,
        "visa_cost_investor": 47500,
        "visa_cost_manager": 37500,
        "visa_cost_employment": 37500,
        "immigration_establishment_card": 16200,
        "e_channel_registration": 0,
        "medical_cost": 4500,
        "eid_cost": 3900,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "11 Visa License",
        "license_cost_including_quota_fee": 34900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 11,
        "visa_cost_investor": 52250,
        "visa_cost_manager": 41250,
        "visa_cost_employment": 41250,
        "immigration_establishment_card": 17820,
        "e_channel_registration": 0,
        "medical_cost": 4950,
        "eid_cost": 4290,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "12 Visa License",
        "license_cost_including_quota_fee": 36900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 12,
        "visa_cost_investor": 57000,
        "visa_cost_manager": 45000,
        "visa_cost_employment": 45000,
        "immigration_establishment_card": 19440,
        "e_channel_registration": 0,
        "medical_cost": 5400,
        "eid_cost": 4680,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "13 Visa License",
        "license_cost_including_quota_fee": 38900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 13,
        "visa_cost_investor": 61750,
        "visa_cost_manager": 48750,
        "visa_cost_employment": 48750,
        "immigration_establishment_card": 21060,
        "e_channel_registration": 0,
        "medical_cost": 5850,
        "eid_cost": 5070,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "14 Visa License",
        "license_cost_including_quota_fee": 40900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 14,
        "visa_cost_investor": 66500,
        "visa_cost_manager": 52500,
        "visa_cost_employment": 52500,
        "immigration_establishment_card": 22680,
        "e_channel_registration": 0,
        "medical_cost": 6300,
        "eid_cost": 5460,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "IFZA",
        "product": "15 Visa License",
        "license_cost_including_quota_fee": 42900,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "7 Mix & Match",
        "visa_eligibility": 15,
        "visa_cost_investor": 71250,
        "visa_cost_manager": 56250,
        "visa_cost_employment": 56250,
        "immigration_establishment_card": 24300,
        "e_channel_registration": 0,
        "medical_cost": 6750,
        "eid_cost": 5850,
        "jurisdiction": "Freezone"
    }
];

// MEYDAN Data
const meydanData = [
    {
        "freezone": "MEYDAN",
        "product": "0 Visa License",
        "license_cost_including_quota_fee": 12520,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 0,
        "visa_cost_investor": 0,
        "visa_cost_manager": 0,
        "visa_cost_employment": 0,
        "immigration_establishment_card": 0,
        "e_channel_registration": 0,
        "medical_cost": 0,
        "eid_cost": 0,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "1 Visa License",
        "license_cost_including_quota_fee": 14370,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 1,
        "visa_cost_investor": 4040,
        "visa_cost_manager": 3520,
        "visa_cost_employment": 3520,
        "immigration_establishment_card": 1670,
        "e_channel_registration": 335,
        "medical_cost": 335,
        "eid_cost": 390,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "2 Visa License",
        "license_cost_including_quota_fee": 16220,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 2,
        "visa_cost_investor": 8080,
        "visa_cost_manager": 7040,
        "visa_cost_employment": 7040,
        "immigration_establishment_card": 3340,
        "e_channel_registration": 670,
        "medical_cost": 670,
        "eid_cost": 780,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "3 Visa License",
        "license_cost_including_quota_fee": 18070,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 3,
        "visa_cost_investor": 12120,
        "visa_cost_manager": 10560,
        "visa_cost_employment": 10560,
        "immigration_establishment_card": 5010,
        "e_channel_registration": 1005,
        "medical_cost": 1005,
        "eid_cost": 1170,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "4 Visa License",
        "license_cost_including_quota_fee": 19920,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 4,
        "visa_cost_investor": 16160,
        "visa_cost_manager": 14080,
        "visa_cost_employment": 14080,
        "immigration_establishment_card": 6680,
        "e_channel_registration": 1340,
        "medical_cost": 1340,
        "eid_cost": 1560,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "5 Visa License",
        "license_cost_including_quota_fee": 21770,
        "office_facility_requirements": "Co-Working/Flexi-Desk",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 5,
        "visa_cost_investor": 20200,
        "visa_cost_manager": 17600,
        "visa_cost_employment": 17600,
        "immigration_establishment_card": 8350,
        "e_channel_registration": 1675,
        "medical_cost": 1675,
        "eid_cost": 1950,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "6 Visa License",
        "license_cost_including_quota_fee": 23620,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 6,
        "visa_cost_investor": 24240,
        "visa_cost_manager": 21120,
        "visa_cost_employment": 21120,
        "immigration_establishment_card": 10020,
        "e_channel_registration": 2010,
        "medical_cost": 2010,
        "eid_cost": 2340,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "7 Visa License",
        "license_cost_including_quota_fee": 25470,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 7,
        "visa_cost_investor": 28280,
        "visa_cost_manager": 24640,
        "visa_cost_employment": 24640,
        "immigration_establishment_card": 11690,
        "e_channel_registration": 2345,
        "medical_cost": 2345,
        "eid_cost": 2730,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "8 Visa License",
        "license_cost_including_quota_fee": 27320,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 8,
        "visa_cost_investor": 32320,
        "visa_cost_manager": 28160,
        "visa_cost_employment": 28160,
        "immigration_establishment_card": 13360,
        "e_channel_registration": 2680,
        "medical_cost": 2680,
        "eid_cost": 3120,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "9 Visa License",
        "license_cost_including_quota_fee": 29170,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 9,
        "visa_cost_investor": 36360,
        "visa_cost_manager": 31680,
        "visa_cost_employment": 31680,
        "immigration_establishment_card": 15030,
        "e_channel_registration": 3015,
        "medical_cost": 3015,
        "eid_cost": 3510,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "10 Visa License",
        "license_cost_including_quota_fee": 31020,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 10,
        "visa_cost_investor": 40400,
        "visa_cost_manager": 35200,
        "visa_cost_employment": 35200,
        "immigration_establishment_card": 16700,
        "e_channel_registration": 3350,
        "medical_cost": 3350,
        "eid_cost": 3900,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "11 Visa License",
        "license_cost_including_quota_fee": 32870,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 11,
        "visa_cost_investor": 44440,
        "visa_cost_manager": 38720,
        "visa_cost_employment": 38720,
        "immigration_establishment_card": 18370,
        "e_channel_registration": 3685,
        "medical_cost": 3685,
        "eid_cost": 4290,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "12 Visa License",
        "license_cost_including_quota_fee": 34720,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 12,
        "visa_cost_investor": 48480,
        "visa_cost_manager": 42240,
        "visa_cost_employment": 42240,
        "immigration_establishment_card": 20040,
        "e_channel_registration": 4020,
        "medical_cost": 4020,
        "eid_cost": 4680,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "13 Visa License",
        "license_cost_including_quota_fee": 36570,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 13,
        "visa_cost_investor": 52520,
        "visa_cost_manager": 45760,
        "visa_cost_employment": 45760,
        "immigration_establishment_card": 21710,
        "e_channel_registration": 4355,
        "medical_cost": 4355,
        "eid_cost": 5070,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "14 Visa License",
        "license_cost_including_quota_fee": 38420,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 14,
        "visa_cost_investor": 56560,
        "visa_cost_manager": 49280,
        "visa_cost_employment": 49280,
        "immigration_establishment_card": 23380,
        "e_channel_registration": 4690,
        "medical_cost": 4690,
        "eid_cost": 5460,
        "jurisdiction": "Freezone"
    },
    {
        "freezone": "MEYDAN",
        "product": "15 Visa License",
        "license_cost_including_quota_fee": 40270,
        "office_facility_requirements": "Physical Office",
        "no_of_activities_allowed_under_license": "3 Mix & Match",
        "visa_eligibility": 15,
        "visa_cost_investor": 60600,
        "visa_cost_manager": 52800,
        "visa_cost_employment": 52800,
        "immigration_establishment_card": 25050,
        "e_channel_registration": 5025,
        "medical_cost": 5025,
        "eid_cost": 5850,
        "jurisdiction": "Freezone"
    }
];

// RAKEZ Data (file continued in next message due to length)
