// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIxAfwEQ5kqPBiPr3Zf5B0oWYdEcKJhZo',
    appId: '1:350415177061:web:1c45ff3565a672d4408d8c',
    messagingSenderId: '350415177061',
    projectId: 'business-setup-application',
    authDomain: 'business-setup-application.firebaseapp.com',
    storageBucket: 'business-setup-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIxAfwEQ5kqPBiPr3Zf5B0oWYdEcKJhZo',
    appId: '1:350415177061:android:1c45ff3565a672d4408d8c',
    messagingSenderId: '350415177061',
    projectId: 'business-setup-application',
    storageBucket: 'business-setup-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-1VRdwcT8Mwq5VoeB6YN1qNdzcRaTns8',
    appId: '1:350415177061:ios:409d8c9ce1d7a993408d8c',
    messagingSenderId: '350415177061',
    projectId: 'business-setup-application',
    storageBucket: 'business-setup-application.firebasestorage.app',
    iosBundleId: 'com.wazeet.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-1VRdwcT8Mwq5VoeB6YN1qNdzcRaTns8',
    appId: '1:350415177061:ios:409d8c9ce1d7a993408d8c',
    messagingSenderId: '350415177061',
    projectId: 'business-setup-application',
    storageBucket: 'business-setup-application.firebasestorage.app',
    iosBundleId: 'com.wazeet.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIxAfwEQ5kqPBiPr3Zf5B0oWYdEcKJhZo',
    appId: '1:350415177061:web:1c45ff3565a672d4408d8c',
    messagingSenderId: '350415177061',
    projectId: 'business-setup-application',
    authDomain: 'business-setup-application.firebaseapp.com',
    storageBucket: 'business-setup-application.firebasestorage.app',
  );
}
