import 'package:flutter/material.dart';

/// Maps icon name strings to Material IconData
IconData getIconData(String iconName) {
  switch (iconName.toLowerCase()) {
    case 'calculate':
      return Icons.calculate;
    case 'corporate_fare':
      return Icons.account_balance;
    case 'inventory':
      return Icons.inventory;
    case 'support_agent':
      return Icons.support_agent;
    case 'assignment_turned_in':
      return Icons.assignment_turned_in;
    case 'help_outline':
      return Icons.help_outline;
    case 'app_registration':
      return Icons.app_registration;
    case 'remove_circle_outline':
      return Icons.remove_circle_outline;
    case 'paid':
      return Icons.paid;
    case 'public':
      return Icons.public;
    case 'tune':
      return Icons.tune;
    case 'confirmation_number':
      return Icons.confirmation_number;
    case 'group_add':
      return Icons.group_add;
    case 'manage_accounts':
      return Icons.manage_accounts;
    case 'person_remove':
      return Icons.person_remove;
    case 'luggage':
      return Icons.luggage;
    case 'storefront':
      return Icons.storefront;
    case 'home':
      return Icons.home;
    case 'mosque':
      return Icons.account_balance; // closest available
    case 'flag_circle':
      return Icons.flag;
    case 'assignment_add':
      return Icons.assignment; // closest available
    case 'category':
      return Icons.category;
    case 'edit':
      return Icons.edit;
    case 'qr_code':
      return Icons.qr_code;
    case 'map':
      return Icons.map;
    case 'autorenew':
      return Icons.autorenew;
    case 'cancel':
      return Icons.cancel;
    case 'warehouse':
      return Icons.warehouse;
    case 'report':
      return Icons.report;
    case 'assignment':
      return Icons.assignment;
    case 'security':
      return Icons.security;
    case 'disabled_by_default':
      return Icons.disabled_by_default;
    case 'person_add':
      return Icons.person_add;
    case 'business':
      return Icons.business;
    case 'link':
      return Icons.link;
    case 'edit_note':
      return Icons.edit_note;
    case 'workspace_premium':
      return Icons.workspace_premium;
    case 'live_help':
      return Icons.live_help;
    case 'question_mark':
      return Icons.question_mark;
    case 'lightbulb':
      return Icons.lightbulb;
    case 'rule':
      return Icons.rule;
    case 'edit_attributes':
      return Icons.edit_attributes;
    case 'flight':
    case 'airplane':
      return Icons.flight;
    case 'account_balance':
    case 'bank':
      return Icons.account_balance;
    case 'receipt_long':
    case 'receipt':
      return Icons.receipt_long;
    case 'account_balance_wallet':
    case 'wallet':
      return Icons.account_balance_wallet;
    case 'description':
    case 'document':
      return Icons.description;
    case 'trending_up':
    case 'growth':
      return Icons.trending_up;
    case 'smartphone':
    case 'phone':
    case 'mobile':
      return Icons.smartphone;
    case 'local_shipping':
    case 'shipping':
    case 'truck':
      return Icons.local_shipping;
    case 'groups':
    case 'people':
      return Icons.groups;
    case 'gavel':
    case 'legal':
      return Icons.gavel;
    case 'diamond':
    case 'gem':
      return Icons.diamond;
    case 'card_travel':
    case 'passport':
      return Icons.card_travel;
    case 'badge':
    case 'id':
      return Icons.badge;
    case 'warning':
    case 'alert':
      return Icons.warning;
    case 'work':
    case 'briefcase':
      return Icons.work;
    case 'hotel':
    case 'bed':
      return Icons.hotel;
    case 'school':
    case 'education':
      return Icons.school;
    case 'language':
    case 'translation':
      return Icons.language;
    case 'medical_services':
    case 'health':
      return Icons.medical_services;
    default:
      return Icons.category; // fallback icon
  }
}
